### ISSUE TITLE
Déconnexion systématique sous Chrome

### ISSUE THREAD

**Issue by gutard** [eedf/vieasso#3]
Je peux me connecter et affiche la home, mais au 1er lien que je clique je suis déconnecté et ramené à la page de login.

**Comment by gutard** [comment]
Le problème se produit sous chrome, pas sous Firefox

**Comment by gutard** [comment]
@DevGoodlink, peux-tu reproduire avec Chrome ?

**Comment by DevGoodlink** [comment]
@gutard J'ai testé sous chrome effectivement il y a ce problème, je viens de régler ça, c'est à cause de la dernière ligne d'urls.py
